# Reference: https://github.com/Homebrew/homebrew-bundle

# Prerequisite, but good to just make sure its there
brew "git"

tap "microsoft/git"
# Prefered credential manager on macOS for GitHub
cask "git-credential-manager-core"

# Open and/or free fonts
tap "homebrew/cask-fonts"
cask "font-fira-code"

# Replacement for cat and man, supporting colorized syntax highlighting
brew "bat"
tap "eth-p/software"
brew "bat-extras-batman"
