#
# Settings for login shells (not dependant on interactivity)
#

# Homebrew initialization (prepends to $PATH)
eval "$(/opt/homebrew/bin/brew shellenv)"

# Go initialization
export GOPATH=~/Developer/go
export PATH=$PATH:$(go env GOPATH)/bin
