#
# Settings for login shells (not dependant on interactivity)
#

# Homebrew initialization (prepends to $PATH)
eval "$(/opt/homebrew/bin/brew shellenv)"

# Go initialization
export GOPATH=~/Developer/go
export PATH=$PATH:$(go env GOPATH)/bin

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
