#
# Settings for interactive shells
#

# Homebrew completions support
# See: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# Pure prompt (https://github.com/sindresorhus/pure)
fpath+=($HOME/.dotfiles/zsh/pure)
autoload -U promptinit; promptinit
# more Pure config here
prompt pure
