#
# Settings for interactive shells
#

#
# Aliases
#

# Moving around directories a bit easier
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

#
# Homebrew completions support
# See: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
#
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

#
# Antidote - ZSH Plugin manager
#
source ${HOME}/.dotfiles/zsh/antidote/antidote.zsh
# Statically load plugins listed in ./zsh_plugins
antidote load ${HOME}/.dotfiles/zsh/zsh_plugins

#
# Pure prompt (https://github.com/sindresorhus/pure)
#
autoload -U promptinit; promptinit
# ... any pure customization goes here ...
prompt pure
